import "./globals.css";
import NavBar from "@/app/homePage/Components/NavBar/NavBar";
import UpperFooter from "@/app/homePage/Components/Footer/UpperFooter";
import LowerFooter from "@/app/homePage/Components/Footer/LowerFooter";






export const metadata = {
  title: "دانشگاه جامع انقلاب اسلامی",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body>
      <NavBar />
        {children}

      <UpperFooter />
      <LowerFooter />
      </body>
    </html>
  );
}
