import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'

const iransans = localFont({
    src: [
        {
            path: '../fonts/iransans/IRANSansXFaNum-Bold.woff',
            weight: '300',
            style: 'normal',
        },
        {
            path: '../fonts/iransans/IRANSansXFaNum-Light.woff',
            weight: 'bold',
            style: 'normal',
        },
        {
            path: '../fonts/iransans/IRANSansXFaNum-Medium.woff',
            weight: '500',
            style: 'normal',
        },
        {
            path: '../fonts/iransans/IRANSansXFaNum-Regular.woff',
            weight: 'normal',
            style: 'normal',
        },
        {
            path: '../fonts/iransans/IRANSansXFaNum-Light.woff',
            weight: '300',
            style: 'normal',
        },

    ],
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable}${geistMono.variable} antialiased ${iransans.className}`}
      >
        {children}
      </body>
    </html>
  );
}
