import './globals.css';
import UpperFooter from './(homepage)/Components/Footer/UpperFooter';
import LowerFooter from './(homepage)/Components/Footer/LowerFooter';
import NavBar from "./(homepage)/Components/NavBar/NavBar"
export const metadata = {
  title: 'دانشگاه جامع انقلاب اسلامی',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body>
      <NavBar />
        {children}
        <UpperFooter />
        <LowerFooter />
      </body>
    </html>
  );
}
