import './globals.css';
import HeaderComponent from '../components/DynamicComponents/HeaderComponent';
import UpperFooterComponent from '../components/Footer/UpperFooter';
import LowerFooterComponent from '../components/Footer/LowerFooter';

export const metadata = {
  title: 'دانشگاه جامع انقلاب اسلامی',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <HeaderComponent />
        {children}
        <UpperFooterComponent />
        <LowerFooterComponent />
      </body>
    </html>
  );
}
